# Generated by Django 2.1.2 on 2018-10-25 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Houses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('salerent', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=5000)),
            ],
        ),
    ]
