# Generated by Django 2.1.2 on 2018-10-25 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userrequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textrequest', models.CharField(max_length=5000)),
            ],
        ),
        migrations.AddField(
            model_name='houses',
            name='userrequest',
            field=models.CharField(default='0', max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userrequests',
            name='linkur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.Houses'),
        ),
    ]
