# Generated by Django 2.1.2 on 2018-11-08 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_auto_20181108_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='salerent',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
